# Generated by Django 4.0.5 on 2022-11-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_autor_email_alter_editora_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='ISBN',
            new_name='isbn',
        ),
    ]
